// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASlJtdOY13Nc-uuc18txKSscfV1GM7Pag',
    appId: '1:2449077978:web:dd04c048446692d2e097e3',
    messagingSenderId: '2449077978',
    projectId: 'vocal-app-pro',
    authDomain: 'vocal-app-pro.firebaseapp.com',
    storageBucket: 'vocal-app-pro.firebasestorage.app',
    measurementId: 'G-E968P6LWXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ixzA6L1_I3dmnTAnBsScu0KdQtEVLVU',
    appId: '1:2449077978:android:5b9a450e9b3ad4e0e097e3',
    messagingSenderId: '2449077978',
    projectId: 'vocal-app-pro',
    storageBucket: 'vocal-app-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTTztIkKKxzRhsUYkQFnREIdX_yyaNb5g',
    appId: '1:2449077978:ios:85ee2920a166c006e097e3',
    messagingSenderId: '2449077978',
    projectId: 'vocal-app-pro',
    storageBucket: 'vocal-app-pro.firebasestorage.app',
    iosClientId: '2449077978-s37vsnn9kqmu595mdh57j87ep80rg4uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocalApp',
  );
}
